name: Apalache

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt install default-jre
          wget https://github.com/informalsystems/apalache/releases/download/v0.29.2/apalache.tgz
          tar zxvf apalache.tgz
      - name: Typecheck
        run: |
          ./apalache/bin/apalache-mc typecheck --features=no-rows MCFPaxosTwoAcc.tla
          ./apalache/bin/apalache-mc typecheck --features=no-rows MCFPaxosThreeAcc.tla
          ./apalache/bin/apalache-mc typecheck --features=no-rows MCFPaxosFourAcc.tla