name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install TLA+ Tools
        run: |
          git clone https://github.com/pmer/tla-bin.git
          cd tla-bin
          ./download_or_update_tla.sh
          sudo ./install.sh
          cd ..
      - name: Sany
        run: sany MCFPaxos.tla
      - name: TLC
        run: tlc MCFPaxos.tla
      - name: Apalache
        run: |
          sudo apt install default-jre
          wget https://github.com/informalsystems/apalache/releases/download/v0.29.2/apalache.tgz
          tar zxvf apalache.tgz
          ./apalache/bin/apalache-mc typecheck --features=no-rows MCFPaxos.tla
