name: TLA+ Tools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TLA+ Tools
        run: |
          git clone https://github.com/pmer/tla-bin.git
          cd tla-bin
          ./download_or_update_tla.sh
          sudo ./install.sh
      - name: Sany
        run: git ls-files | grep -F ".tla" | xargs sany
      - name: TLC
        run: git ls-files | grep 'MC.*\.tla' | xargs tlc -config MCFPaxos.cfg -workers auto
      - name: Install LaTeX
        run: sudo apt install texlive-latex-recommended
      - name: TLA+ pretty printer
        run: |
          tlatex FPaxos.tla
          pdflatex FPaxos.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Pretty Printed TLA+ Specification
          path: FPaxos.pdf