name: TLA+ Tools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install TLA+ Tools
        run: |
          git clone https://github.com/pmer/tla-bin.git
          cd tla-bin
          ./download_or_update_tla.sh
          sudo ./install.sh
      - name: Sany (All)
        run: |
          sany MCFPaxosTwoAcc.tla
          sany MCFPaxosThreeAcc.tla
          sany MCFPaxosFourAcc.tla
      - name: TLC - 2 Acceptors
        run: tlc -config MCFPaxos.cfg -workers auto MCFPaxosTwoAcc.tla
      - name: TLC - 3 Acceptors
        run: tlc -config MCFPaxos.cfg -workers auto MCFPaxosThreeAcc.tla
      - name: TLC - 4 Acceptors
        run: tlc -config MCFPaxos.cfg -workers auto MCFPaxosFourAcc.tla